export type AdditionalMarket = {
  name: string;
  ticker: string;
  category:
    | "Music"
    | "Sport"
    | "Film"
    | "TV"
    | "Politics"
    | "Fashion"
    | "Digital"
    | "Comedy";
  birthYear: number;
  nationality: string;
  image: string;
  change: number;
  signals: {
    socialFollowersMillions: number;
    hashtagViewsBillions: number;
    trendScore: number;
    monthlySearchesMillions: number;
    newsStories: number;
  };
};

type Profile = [
  string,
  string,
  AdditionalMarket["category"],
  number,
  number,
  string?, // nationality optional, default British
];

const profiles: Profile[] = [
  // MUSIC (Pop, Hip-hop, Rock, Electronic, R&B)
  ["Elton John", "ELTON", "Music", 1947, 4.9, "British"],
  ["Robbie Williams", "ROBBIE", "Music", 1974, 4.7, "British"],
  ["Jessie J", "JESSIEJ", "Music", 1988, 3.6, "British"],
  ["Rita Ora", "RITAORA", "Music", 1990, 5.2, "British"],
  ["Sam Smith", "SAMSMITH", "Music", 1992, 6.8, "British"],
  ["Florence Welch", "FLORENCE", "Music", 1986, 4.1, "British"],
  ["Liam Gallagher", "LIAMG", "Music", 1972, 2.9, "British"],
  ["Noel Gallagher", "NOELG", "Music", 1967, 2.6, "British"],
  ["Damon Albarn", "DAMON", "Music", 1968, 2.2, "British"],
  ["Skepta", "SKEPTA", "Music", 1982, 7.4, "British"],
  ["Dave", "SANTANDAVE", "Music", 1998, 10.3, "British"],
  ["Central Cee", "CENTRALC", "Music", 1998, 12.1, "British"],
  ["Little Simz", "LITTLESIMZ", "Music", 1994, 8.2, "British"],
  ["Jorja Smith", "JORJASMITH", "Music", 1997, 6.4, "British"],
  ["Raye", "RAYE", "Music", 1997, 11.6, "British"],
  ["Charli XCX", "CHARLI", "Music", 1992, 14.5, "British"],
  ["Mabel", "MABEL", "Music", 1996, 3.8, "British"],
  ["Anne-Marie", "ANNEMARIE", "Music", 1991, 4.4, "British"],
  ["Lewis Capaldi", "LEWISC", "Music", 1996, 7.9, "British"],
  ["Tom Grennan", "TOMG", "Music", 1995, 5.1, "British"],
  ["Yungblud", "YUNGBLUD", "Music", 1997, 9.6, "British"],
  ["FKA twigs", "FKATWIGS", "Music", 1988, 6.7, "British"],
  ["M.I.A.", "MIA", "Music", 1975, 2.1, "British"],
  ["Shania Twain", "SHANIA", "Music", 1965, 1.9, "Canadian"],
  ["Niall Horan", "NIALL", "Music", 1993, 4.6, "Irish"],
  ["Zayn Malik", "ZAYN", "Music", 1993, 6.9, "British"],
  ["Louis Tomlinson", "LTOMLINSON", "Music", 1991, 5.4, "British"],
  ["Calvin Harris", "CALVINH", "Music", 1984, 6.1, "British"],
  ["Fred again..", "FREDAGAIN", "Music", 1993, 13.8, "British"],
  ["PinkPantheress", "PINKP", "Music", 2001, 11.2, "British"],
  ["Gorillaz", "GORILLAZ", "Music", 1998, 4.3, "British"],
  ["Coldplay", "COLDPLAY", "Music", 1997, 8.7, "British"],
  ["Muse", "MUSE", "Music", 1994, 3.4, "British"],
  ["Arctic Monkeys", "ARCTICM", "Music", 2002, 7.9, "British"],
  ["The 1975", "THE1975", "Music", 2002, 6.5, "British"],
  ["Arlo Parks", "ARLOPARKS", "Music", 2000, 5.8, "British"],
  ["Sam Fender", "SAMFENDER", "Music", 1994, 9.2, "British"],
  ["Declan McKenna", "DECLANMCK", "Music", 1998, 4.2, "British"],
  ["Beabadoobee", "BEABADOOBEE", "Music", 2000, 8.4, "British"],
  ["Burna Boy", "BURNABOY", "Music", 1991, 10.7, "Nigerian"],
  ["Wizkid", "WIZKID", "Music", 1990, 8.3, "Nigerian"],
  ["Asake", "ASAKE", "Music", 1995, 9.5, "Nigerian"],
  ["Rema", "REMA", "Music", 2000, 11.8, "Nigerian"],
  ["Tyla", "TYLA", "Music", 2002, 13.4, "South African"],
  ["Sabrina Carpenter", "SCARPENTER", "Music", 1999, 15.6, "American"],
  ["Olivia Rodrigo", "ORODRIGO", "Music", 2003, 14.1, "American"],
  ["Billie Eilish", "BEILISH", "Music", 2001, 12.9, "American"],
  ["Chappell Roan", "CHAPPELL", "Music", 1998, 16.2, "American"],
  ["The Weeknd", "THEWEEKND", "Music", 1990, 11.5, "Canadian"],
  ["Drake", "DRAKE", "Music", 1986, 9.8, "Canadian"],
  ["Post Malone", "POSTMALONE", "Music", 1995, 8.1, "American"],
  ["Kendrick Lamar", "KENDRICK", "Music", 1987, 13.7, "American"],
  ["Travis Scott", "TRAVISS", "Music", 1991, 10.4, "American"],
  ["Jack Harlow", "JACKHARLOW", "Music", 1998, 7.2, "American"],
  ["Beyonce", "BEYONCE", "Music", 1981, 12.3, "American"],
  ["Katy Perry", "KPERRY", "Music", 1984, 5.1, "American"],
  ["Lady Gaga", "LADYGAGA", "Music", 1986, 9.4, "American"],
  ["Ariana Grande", "ARIANA", "Music", 1993, 11.9, "American"],
  ["Kylie Minogue", "KYLIE", "Music", 1968, 6.8, "Australian"],
  ["Troye Sivan", "TROYESIVAN", "Music", 1995, 8.9, "Australian"],

  // SPORT (Football, Formula 1, Tennis, Boxing, Athletics, Cricket, Rugby, Darts)
  ["Marcus Rashford", "RASHFORD", "Sport", 1997, 8.4, "British"],
  ["Harry Kane", "HKANE", "Sport", 1993, 4.3, "British"],
  ["Raheem Sterling", "STERLING", "Sport", 1994, 2.7, "British"],
  ["Phil Foden", "FODEN", "Sport", 2000, 10.2, "British"],
  ["Declan Rice", "RICE", "Sport", 1999, 7.1, "British"],
  ["Jack Grealish", "GREALISH", "Sport", 1995, 5.4, "British"],
  ["Cole Palmer", "CPALMER", "Sport", 2002, 14.8, "British"],
  ["Kobbie Mainoo", "MAINOO", "Sport", 2005, 12.4, "British"],
  ["Ollie Watkins", "OWATKINS", "Sport", 1995, 7.6, "British"],
  ["Anthony Gordon", "AGORDON", "Sport", 2001, 6.9, "British"],
  ["Trent Alexander-Arnold", "TAA", "Sport", 1998, 8.7, "British"],
  ["Erling Haaland", "HAALAND", "Sport", 2000, 13.9, "Norwegian"],
  ["Kylian Mbappe", "MBAPPE", "Sport", 1998, 14.5, "French"],
  ["Vinicius Jr", "VINICIUS", "Sport", 2000, 13.1, "Brazilian"],
  ["Lamine Yamal", "LAMINE", "Sport", 2007, 16.9, "Spanish"],
  ["Lionel Messi", "MESSI", "Sport", 1987, 10.8, "Argentine"],
  ["Neymar Jr", "NEYMAR", "Sport", 1992, 7.4, "Brazilian"],
  ["Son Heung-min", "SONNY", "Sport", 1992, 8.1, "South Korean"],
  ["Mary Earps", "EARPS", "Sport", 1993, 9.8, "British"],
  ["Lauren James", "LAURENJ", "Sport", 2001, 8.8, "British"],
  ["Beth Mead", "BETHMEAD", "Sport", 1995, 4.1, "British"],
  ["Millie Bright", "MBRIGHT", "Sport", 1993, 3.7, "British"],
  ["Lucy Bronze", "BRONZE", "Sport", 1991, 4.6, "British"],
  ["Fran Kirby", "FKIRBY", "Sport", 1993, 3.7, "British"],
  ["Georgia Stanway", "GSTANWAY", "Sport", 1999, 5.4, "British"],
  ["Alessia Russo", "RUSSO", "Sport", 1999, 9.1, "British"],
  ["Chloe Kelly", "CKELLY", "Sport", 1998, 7.8, "British"],
  ["Alexia Putellas", "PUTELLAS", "Sport", 1994, 8.3, "Spanish"],
  ["Aitana Bonmati", "BONMATI", "Sport", 1998, 11.4, "Spanish"],
  ["Sam Kerr", "SAMKERR", "Sport", 1993, 7.2, "Australian"],
  ["Lando Norris", "LNORRIS", "Sport", 1999, 13.6, "British"],
  ["George Russell", "GRUSSELL", "Sport", 1998, 8.2, "British"],
  ["Max Verstappen", "VERSTAPPEN", "Sport", 1997, 12.1, "Dutch"],
  ["Charles Leclerc", "LECLERC", "Sport", 1997, 11.5, "Monegasque"],
  ["Oscar Piastri", "PIASTRI", "Sport", 2001, 10.9, "Australian"],
  ["Carlos Sainz", "SAINZ", "Sport", 1994, 7.8, "Spanish"],
  ["Fernando Alonso", "ALONSO", "Sport", 1981, 6.4, "Spanish"],
  ["Andy Murray", "MURRAY", "Sport", 1987, 3.2, "British"],
  ["Cameron Norrie", "CNORRIE", "Sport", 1995, 3.8, "British"],
  ["Jack Draper", "JDRAPER", "Sport", 2001, 10.5, "British"],
  ["Carlos Alcaraz", "ALCARAZ", "Sport", 2003, 14.7, "Spanish"],
  ["Jannik Sinner", "SINNER", "Sport", 2001, 13.9, "Italian"],
  ["Novak Djokovic", "DJOKOVIC", "Sport", 1987, 8.5, "Serbian"],
  ["Coco Gauff", "CGAUFF", "Sport", 2004, 12.2, "American"],
  ["Iga Swiatek", "SWIATEK", "Sport", 2001, 11.1, "Polish"],
  ["Aryna Sabalenka", "SABALENKA", "Sport", 1998, 10.6, "Belarusian"],
  ["Anthony Joshua", "AJOSHUA", "Sport", 1989, 7.1, "British"],
  ["Tyson Fury", "FURY", "Sport", 1988, 5.8, "British"],
  ["Oleksandr Usyk", "USYK", "Sport", 1987, 11.3, "Ukrainian"],
  ["Canelo Alvarez", "CANELO", "Sport", 1990, 8.4, "Mexican"],
  ["Katie Taylor", "KTAYLOR", "Sport", 1986, 6.9, "Irish"],
  ["Luke Littler", "LITTLER", "Sport", 2007, 15.8, "British"],
  ["Luke Humphries", "HUMPHRIES", "Sport", 1995, 8.9, "British"],
  ["Michael van Gerwen", "MVG", "Sport", 1989, 5.2, "Dutch"],
  ["Rory McIlroy", "RMCILROY", "Sport", 1989, 4.6, "British"],
  ["Ben Stokes", "BSTOKES", "Sport", 1991, 3.9, "British"],
  ["Joe Root", "JROOT", "Sport", 1990, 3.1, "British"],
  ["Tom Daley", "TDALEY", "Sport", 1994, 6.2, "British"],
  ["Adam Peaty", "PEATY", "Sport", 1994, 4.8, "British"],
  ["Keely Hodgkinson", "KEELYH", "Sport", 2002, 13.5, "British"],
  ["Katarina Johnson-Thompson", "KJT", "Sport", 1993, 7.3, "British"],
  ["Dina Asher-Smith", "DAS", "Sport", 1995, 5.5, "British"],
  ["LeBron James", "LEBRON", "Sport", 1984, 11.2, "American"],
  ["Stephen Curry", "SCURRY", "Sport", 1988, 10.4, "American"],
  ["Patrick Mahomes", "MAHOMES", "Sport", 1995, 9.8, "American"],
  ["Travis Kelce", "TKELCE", "Sport", 1989, 12.7, "American"],

  // FILM (Actors, Directors, Screen Icons)
  ["Emma Watson", "EWATSON", "Film", 1990, 5.8, "British"],
  ["Tom Holland", "THOLLAND", "Film", 1996, 12.4, "British"],
  ["Benedict Cumberbatch", "BCUMBER", "Film", 1976, 4.2, "British"],
  ["Keira Knightley", "KEIRA", "Film", 1985, 3.9, "British"],
  ["Carey Mulligan", "MULLIGAN", "Film", 1985, 3.3, "British"],
  ["Tilda Swinton", "TILDA", "Film", 1960, 2.8, "British"],
  ["Hugh Grant", "HUGHG", "Film", 1960, 3.1, "British"],
  ["Colin Firth", "CFIRTH", "Film", 1960, 2.6, "British"],
  ["Gary Oldman", "GOLDMAN", "Film", 1958, 3.5, "British"],
  ["Helen Mirren", "HMIRREN", "Film", 1945, 3.7, "British"],
  ["Jodie Comer", "JCOMER", "Film", 1993, 10.8, "British"],
  ["Vanessa Kirby", "VKIRBY", "Film", 1988, 5.6, "British"],
  ["Lashana Lynch", "LLYNCH", "Film", 1987, 5.3, "British"],
  ["Letitia Wright", "LWRIGHT", "Film", 1993, 6.2, "British"],
  ["Dev Patel", "DPATEL", "Film", 1990, 7.6, "British"],
  ["Henry Cavill", "HCAVILL", "Film", 1983, 8.7, "British"],
  ["Orlando Bloom", "OBLOOM", "Film", 1977, 3.8, "British"],
  ["Jason Statham", "JSTATHAM", "Film", 1967, 4.4, "British"],
  ["Daniel Craig", "DCRAIG", "Film", 1968, 4.9, "British"],
  ["Taron Egerton", "TEGERTON", "Film", 1989, 5.1, "British"],
  ["Anya Taylor-Joy", "ANYATJ", "Film", 1996, 13.2, "British"],
  ["Robert Pattinson", "RPATT", "Film", 1986, 6.6, "British"],
  ["Paul Mescal", "PMESCAL", "Film", 1996, 11.3, "Irish"],
  ["Saoirse Ronan", "SRONAN", "Film", 1994, 8.5, "Irish"],
  ["Barry Keoghan", "BKEOGHAN", "Film", 1992, 9.4, "Irish"],
  ["Andrew Scott", "ASCOTT_ACTOR", "Film", 1976, 8.9, "Irish"],
  ["Colin Farrell", "CFARRELL", "Film", 1976, 7.8, "Irish"],
  ["Florence Pugh", "FPUGH", "Film", 1996, 13.8, "British"],
  ["Daisy Edgar-Jones", "DEJONES", "Film", 1998, 9.2, "British"],
  ["Jacob Elordi", "JELORDI", "Film", 1997, 14.3, "Australian"],
  ["Timothee Chalamet", "CHALAMET", "Film", 1995, 15.4, "American"],
  ["Austin Butler", "ABUTLER", "Film", 1991, 10.9, "American"],
  ["Margot Robbie", "MROBBIE", "Film", 1990, 13.5, "Australian"],
  ["Ryan Gosling", "RGOSLING", "Film", 1980, 10.7, "Canadian"],
  ["Cillian Murphy", "MURPHY_FILM", "Film", 1976, 11.2, "Irish"],
  ["Christopher Nolan", "CNOLAN", "Film", 1970, 9.6, "British"],
  ["Greta Gerwig", "GGERWIG", "Film", 1983, 8.8, "American"],
  ["Denis Villeneuve", "DENISV", "Film", 1967, 7.9, "Canadian"],
  ["Mia Goth", "MIAGOTH", "Film", 1993, 8.7, "British"],
  ["Harris Dickinson", "HDICKINSON", "Film", 1996, 6.7, "British"],
  ["Josh O'Connor", "JOCONNOR", "Film", 1990, 6.5, "British"],
  ["Tom Hardy", "THARDY", "Film", 1977, 6.9, "British"],
  ["Kate Winslet", "KWINSLET", "Film", 1975, 5.6, "British"],
  ["Emily Blunt", "EBLUNT", "Film", 1983, 9.5, "British"],
  ["Lily James", "LJAMES", "Film", 1989, 6.5, "British"],
  ["John Boyega", "JBOYEGA", "Film", 1992, 6.9, "British"],
  ["Will Poulter", "WPOULTER", "Film", 1993, 6.2, "British"],
  ["Nicholas Hoult", "NHOULT", "Film", 1989, 5.5, "British"],
  ["Tom Hiddleston", "THIDDLES", "Film", 1981, 6.1, "British"],
  ["Eddie Redmayne", "EREDMAYNE", "Film", 1982, 4.8, "British"],
  ["Gemma Chan", "GCHAN", "Film", 1982, 5.4, "British"],
  ["Sophie Turner", "STURNER", "Film", 1996, 6.7, "British"],

  // TV & ENTERTAINMENT (Stars, Hosts, Dramas)
  ["Millie Bobby Brown", "MBB", "TV", 2004, 12.3, "British"],
  ["Phoebe Waller-Bridge", "PWB", "TV", 1985, 6.6, "British"],
  ["Michaela Coel", "MCOEL", "TV", 1987, 7.5, "British"],
  ["Olivia Cooke", "OCOOKE", "TV", 1993, 8.2, "British"],
  ["Ayo Edebiri", "AYO", "TV", 1995, 12.6, "American"],
  ["Ncuti Gatwa", "NCUTI", "TV", 1992, 10.7, "British"],
  ["Jenna Coleman", "JCOLEMAN", "TV", 1986, 5.9, "British"],
  ["David Tennant", "DTENNANT", "TV", 1971, 7.2, "British"],
  ["Matt Smith", "MATTS", "TV", 1982, 6.4, "British"],
  ["Bella Ramsey", "BRAMSEY", "TV", 2003, 10.1, "British"],
  ["Pedro Pascal", "PPASCAL", "TV", 1975, 14.2, "Chilean"],
  ["Jeremy Allen White", "JAWHITE", "TV", 1991, 13.9, "American"],
  ["Ebon Moss-Bachrach", "EBONMB", "TV", 1977, 8.4, "American"],
  ["Nicola Coughlan", "NCOUGHLAN", "TV", 1987, 12.8, "Irish"],
  ["Simone Ashley", "SASHLEY", "TV", 1995, 10.4, "British"],
  ["Jonathan Bailey", "JBAILEY", "TV", 1988, 11.1, "British"],
  ["Rege-Jean Page", "RJPAGE", "TV", 1988, 8.6, "British"],
  ["Kit Connor", "KITCONNOR", "TV", 2004, 9.7, "British"],
  ["Joe Locke", "JLOCKE", "TV", 2003, 7.8, "British"],
  ["Yasmin Finney", "YFINNEY", "TV", 2003, 7.4, "British"],
  ["Claudia Winkleman", "CWINKLE", "TV", 1972, 5.4, "British"],
  ["Alison Hammond", "AHAMMOND", "TV", 1975, 6.1, "British"],
  ["Graham Norton", "GNORTON", "TV", 1963, 4.3, "Irish"],
  ["Stacey Solomon", "SSOLOMON", "TV", 1989, 6.8, "British"],
  ["Rylan Clark", "RYLAN", "TV", 1989, 4.1, "British"],
  ["Maya Jama", "MAYAJAMA_TV", "TV", 1994, 9.8, "British"],
  ["Davina McCall", "DMCCALL", "TV", 1967, 4.8, "British"],
  ["Martin Lewis", "MLEWIS", "TV", 1972, 7.3, "British"],
  ["Louis Theroux", "LTHEROUX", "TV", 1970, 8.5, "British"],
  ["Stephen Graham", "SGRAHAM_TV", "TV", 1973, 8.1, "British"],
  ["Vicky McClure", "VMCCLURE_TV", "TV", 1983, 4.5, "British"],
  ["Keeley Hawes", "KHAWES_TV", "TV", 1976, 4.2, "British"],
  ["Suranne Jones", "SJONES_TV", "TV", 1978, 4.8, "British"],
  ["Sarah Lancashire", "SLANCASHIRE", "TV", 1964, 6.7, "British"],

  // FASHION & BEAUTY
  ["Naomi Campbell", "NAOMIC", "Fashion", 1970, 6.4, "British"],
  ["Kate Moss", "KATEMOSS", "Fashion", 1974, 5.8, "British"],
  ["Cara Delevingne", "CARAD", "Fashion", 1992, 7.3, "British"],
  ["Alexa Chung", "ALEXAC", "Fashion", 1983, 4.9, "British"],
  ["Jourdan Dunn", "JDUNN", "Fashion", 1990, 5.1, "British"],
  ["Adwoa Aboah", "ADWOAA", "Fashion", 1992, 4.6, "British"],
  ["Paloma Elsesser", "PALOMAE", "Fashion", 1992, 6.8, "American"],
  ["Gigi Hadid", "GIGIH", "Fashion", 1995, 8.2, "American"],
  ["Kendall Jenner", "KJENNER", "Fashion", 1995, 11.4, "American"],
  ["Hailey Bieber", "HBIEBER", "Fashion", 1996, 12.9, "American"],
  ["Kylie Jenner", "KYLIEJ", "Fashion", 1997, 10.3, "American"],
  ["Victoria Beckham", "VBECKHAM_FASHION", "Fashion", 1974, 5.5, "British"],
  ["Jonathan Anderson", "JWANDERSON", "Fashion", 1984, 8.7, "British"],
  ["Daniel Lee", "DANIELLEE", "Fashion", 1986, 6.2, "British"],
  ["Iris Law", "IRISLAW", "Fashion", 2000, 7.1, "British"],
  ["Lila Moss", "LILAMOSS", "Fashion", 2002, 6.9, "British"],
  ["Mia Regan", "MIAREGAN", "Fashion", 2002, 5.4, "British"],
  ["Matty Bovan", "MBOVAN", "Fashion", 1990, 4.1, "British"],

  // DIGITAL & CREATORS (YouTube, TikTok, Podcasters, Streamers)
  ["Sidemen", "SIDEMEN", "Digital", 1990, 9.4, "British"],
  ["W2S", "W2S", "Digital", 1996, 7.8, "British"],
  ["Miniminter", "MINIMINTER", "Digital", 1992, 6.9, "British"],
  ["TBJZL", "TBJZL", "Digital", 1993, 5.7, "British"],
  ["Behzinga", "BEHZINGA", "Digital", 1995, 6.4, "British"],
  ["Zerkaa", "ZERKAA", "Digital", 1992, 5.5, "British"],
  ["Vikkstar123", "VIKKSTAR", "Digital", 1995, 7.1, "British"],
  ["TommyInnit", "TOMMYINNIT", "Digital", 2004, 8.6, "British"],
  ["GeorgeNotFound", "GEORGENF", "Digital", 1996, 6.2, "British"],
  ["Wilbur Soot", "WILBURS", "Digital", 1996, 4.3, "British"],
  ["DanTDM", "DANTDM", "Digital", 1991, 6.8, "British"],
  ["Chunkz", "CHUNKZ", "Digital", 1996, 9.8, "British"],
  ["Yung Filly", "YUNGFILLY", "Digital", 1995, 8.4, "British"],
  ["Harry Pinero", "HPINERO", "Digital", 1991, 6.7, "British"],
  ["Darkest Man", "DARKESTMAN", "Digital", 1997, 7.3, "British"],
  ["Nella Rose", "NELLAROSE", "Digital", 1997, 8.9, "British"],
  ["GK Barry", "GKBARRY", "Digital", 1999, 11.4, "British"],
  ["Madeline Argy", "MARGY", "Digital", 2000, 9.6, "British"],
  ["Max Fosh", "MAXFOSH", "Digital", 1995, 9.2, "British"],
  ["Niko Omilana", "NIKOO", "Digital", 1998, 10.1, "British"],
  ["ChrisMD", "CHRISMD", "Digital", 1996, 6.5, "British"],
  ["IShowSpeed", "SPEED", "Digital", 2005, 16.4, "American"],
  ["Kai Cenat", "KAICENAT", "Digital", 2001, 15.8, "American"],
  ["Emma Chamberlain", "ECHAMBERLAIN", "Digital", 2001, 10.2, "American"],
  ["Alex Cooper", "ACOOPER", "Digital", 1994, 11.9, "American"],
  ["Alix Earle", "ALIXEARLE", "Digital", 2000, 12.5, "American"],
  ["Joe Rogan", "JROGAN", "Digital", 1967, 10.8, "American"],
  ["Steven Bartlett", "SBARTLETT", "Digital", 1992, 8.7, "British"],

  // COMEDY (Stand-ups, Panelists, Satirists)
  ["Mo Gilligan", "MOGILL", "Comedy", 1988, 5.2, "British"],
  ["Joe Lycett", "JLYCETT", "Comedy", 1988, 5.5, "British"],
  ["Jack Whitehall", "JWHITEHALL", "Comedy", 1988, 5.6, "British"],
  ["Katherine Ryan", "KRYAN", "Comedy", 1983, 4.5, "Canadian"],
  ["Sarah Millican", "SMILLICAN", "Comedy", 1975, 3.8, "British"],
  ["Dawn French", "DFRENCH", "Comedy", 1957, 2.7, "British"],
  ["Jennifer Saunders", "JSAUNDERS", "Comedy", 1958, 2.8, "British"],
  ["Matt Lucas", "MLUCAS", "Comedy", 1974, 3.1, "British"],
  ["Noel Fielding", "NFIELDING", "Comedy", 1973, 3.7, "British"],
  ["Ricky Gervais", "RGERVAIS", "Comedy", 1961, 5.3, "British"],
  ["Steve Coogan", "SCOOGAN", "Comedy", 1965, 3.5, "British"],
  ["Rob Brydon", "RBRYDON", "Comedy", 1965, 2.7, "British"],
  ["David Mitchell", "DMITCHELL", "Comedy", 1974, 3.9, "British"],
  ["Victoria Coren Mitchell", "VCM", "Comedy", 1972, 3.3, "British"],
  ["Jimmy Carr", "JCARR", "Comedy", 1972, 3.4, "British"],
  ["Greg Davies", "GDAVIES", "Comedy", 1968, 4.4, "British"],
  ["Richard Ayoade", "RAYOADE", "Comedy", 1977, 3.2, "British"],
  ["Munya Chawawa", "MCHAWAWA", "Comedy", 1992, 5.6, "British"],
  ["Bob Mortimer", "BMORTIMER", "Comedy", 1959, 3.9, "British"],
  ["Fern Brady", "FERNBRADY", "Comedy", 1986, 6.1, "British"],
  ["Maisie Adam", "MAISIEADAM", "Comedy", 1994, 5.4, "British"],
  ["Phil Wang", "PHILWANG", "Comedy", 1990, 4.8, "British"],
  ["Ed Gamble", "EDGAMBLE", "Comedy", 1986, 5.2, "British"],
  ["Nish Kumar", "NISHKUMAR", "Comedy", 1985, 3.9, "British"],
  ["Josh Widdicombe", "JWIDDICOMBE", "Comedy", 1983, 4.2, "British"],
  ["Rob Beckett", "ROBBECKETT", "Comedy", 1986, 4.9, "British"],
  ["Guz Khan", "GUZKHAN", "Comedy", 1986, 5.8, "British"],

  // POLITICS & PUBLIC AFFAIRS
  ["Angela Rayner", "RAYNER", "Politics", 1980, 5.7, "British"],
  ["Rachel Reeves", "RREEVES", "Politics", 1979, 4.2, "British"],
  ["David Lammy", "LAMMY", "Politics", 1972, 3.8, "British"],
  ["Wes Streeting", "STREETING", "Politics", 1983, 4.4, "British"],
  ["Ed Miliband", "EMILIBAND", "Politics", 1969, 3.1, "British"],
  ["Kemi Badenoch", "BADENOCH", "Politics", 1980, 6.4, "British"],
  ["James Cleverly", "CLEVERLY", "Politics", 1969, 3.3, "British"],
  ["Suella Braverman", "BRAVERMAN", "Politics", 1980, 4.8, "British"],
  ["Jeremy Hunt", "JHUNT", "Politics", 1966, 2.5, "British"],
  ["Boris Johnson", "BORISJ", "Politics", 1964, 5.9, "British"],
  ["Theresa May", "TMAY", "Politics", 1956, 2.1, "British"],
  ["Tony Blair", "TBLAIR", "Politics", 1953, 3.4, "British"],
  ["Gordon Brown", "GBROWN", "Politics", 1951, 2.4, "British"],
  ["Ed Davey", "EDDAVEY", "Politics", 1965, 4.9, "British"],
  ["Carla Denyer", "DENYER", "Politics", 1985, 4.1, "British"],
  ["Adrian Ramsay", "ARAMSAY", "Politics", 1981, 3.2, "British"],
  ["John Swinney", "SWINNEY", "Politics", 1964, 2.9, "British"],
  ["Humza Yousaf", "HYOUSAF", "Politics", 1985, 3.6, "British"],
  ["Nicola Sturgeon", "STURGEON", "Politics", 1970, 3.7, "British"],
  ["Andy Burnham", "BURNHAM", "Politics", 1970, 5.2, "British"],
  ["Tracy Brabin", "BRABIN", "Politics", 1961, 2.8, "British"],
  ["Richard Tice", "RTICE", "Politics", 1964, 3.9, "British"],
];

function profileImage(ticker: string) {
  return `/api/celebrity-images/${encodeURIComponent(ticker)}`;
}

export const additionalCelebrityMarkets: AdditionalMarket[] = profiles.map(
  ([name, ticker, category, birthYear, change, nationality = "British"], index) => ({
    name,
    ticker: ticker.replaceAll(" ", ""),
    category,
    birthYear,
    nationality,
    image: profileImage(ticker),
    change,
    signals: {
      socialFollowersMillions: Number((1.8 + (index % 24) * 0.95).toFixed(1)),
      hashtagViewsBillions: Number((0.9 + (index % 18) * 0.65).toFixed(1)),
      trendScore: 65 + (index % 33),
      monthlySearchesMillions: Number((1.4 + (index % 16) * 0.82).toFixed(1)),
      newsStories: 160 + (index % 22) * 45,
    },
  }),
);