export type AdditionalMarket = {
  name: string;
  ticker: string;
  category:
    | "Music"
    | "Sport"
    | "Film"
    | "TV"
    | "Politics"
    | "Fashion"
    | "Digital"
    | "Comedy";
  birthYear: number;
  nationality: string;
  image: string;
  change: number;
  signals: {
    socialFollowersMillions: number;
    hashtagViewsBillions: number;
    trendScore: number;
    monthlySearchesMillions: number;
    newsStories: number;
  };
};

type Profile = [
  string,
  string,
  AdditionalMarket["category"],
  number,
  number,
  string?, // nationality optional, default British
];

const profiles: Profile[] = [
  // K-POP GLOBAL SUPERSTARS
  ["Jungkook", "JUNGKOOK", "Music", 1997, 15.8, "South Korean"],
  ["Jimin", "JIMIN", "Music", 1995, 14.9, "South Korean"],
  ["V", "V_BTS", "Music", 1995, 15.2, "South Korean"],
  ["RM", "RMBTS", "Music", 1994, 12.4, "South Korean"],
  ["Suga", "SUGA", "Music", 1993, 13.1, "South Korean"],
  ["Jin", "JINBTS", "Music", 1992, 13.6, "South Korean"],
  ["J-Hope", "JHOPE", "Music", 1994, 12.8, "South Korean"],
  ["Jennie", "JENNIE", "Music", 1996, 16.4, "South Korean"],
  ["Lisa", "LISAMUSIC", "Music", 1997, 16.9, "Thai"],
  ["Jisoo", "JISOO", "Music", 1995, 14.7, "South Korean"],
  ["Rosé", "ROSEPARK", "Music", 1997, 15.3, "South Korean"],
  ["Stray Kids", "STRAYKIDS", "Music", 2017, 14.1, "South Korean"],
  ["Felix", "FELIXSKZ", "Music", 2000, 13.9, "Australian"],
  ["NewJeans", "NEWJEANS", "Music", 2022, 14.8, "South Korean"],
  ["Hanni", "HANNINJ", "Music", 2004, 13.2, "Vietnamese"],
  ["aespa", "AESPA", "Music", 2020, 13.5, "South Korean"],
  ["Karina", "KARINAAESPA", "Music", 2000, 14.4, "South Korean"],
  ["IU", "IU_LEE", "Music", 1993, 11.7, "South Korean"],
  ["Cha Eun-woo", "CHAEUNWOO", "TV", 1997, 13.8, "South Korean"],
  ["SEVENTEEN", "SEVENTEEN", "Music", 2015, 12.9, "South Korean"],
  ["Enhypen", "ENHYPEN", "Music", 2020, 12.3, "South Korean"],
  ["TWICE", "TWICE", "Music", 2015, 11.8, "South Korean"],
  ["Nayeon", "NAYEON", "Music", 1995, 12.5, "South Korean"],

  // TV & ENTERTAINMENT (Stars, Hosts, Dramas, Sitcoms, Reality)
  ["Millie Bobby Brown", "MBB", "TV", 2004, 12.3, "British"],
  ["Sydney Sweeney", "SSWEENEY", "TV", 1997, 16.2, "American"],
  ["Jenna Ortega", "JORTEGA", "TV", 2002, 15.7, "American"],
  ["Jennifer Aniston", "JANISTON", "TV", 1969, 7.8, "American"],
  ["Courteney Cox", "CCOX", "TV", 1964, 4.2, "American"],
  ["Lisa Kudrow", "LKUDROW", "TV", 1963, 3.8, "American"],
  ["Matt LeBlanc", "MLEBLANC", "TV", 1967, 3.9, "American"],
  ["David Schwimmer", "DSCHWIMMER", "TV", 1966, 3.6, "American"],
  ["Steve Carell", "SCARELL", "TV", 1962, 6.4, "American"],
  ["Bryan Cranston", "BCRANSTON", "TV", 1956, 8.2, "American"],
  ["Aaron Paul", "APAUL", "TV", 1979, 6.1, "American"],
  ["Bob Odenkirk", "BODENKIRK", "TV", 1962, 5.7, "American"],
  ["Walton Goggins", "WGOGGINS", "TV", 1971, 11.8, "American"],
  ["Pedro Pascal", "PPASCAL", "TV", 1975, 14.2, "Chilean"],
  ["Jeremy Allen White", "JAWHITE", "TV", 1991, 13.9, "American"],
  ["Ebon Moss-Bachrach", "EBONMB", "TV", 1977, 8.4, "American"],
  ["Ayo Edebiri", "AYO", "TV", 1995, 12.6, "American"],
  ["Sarah Snook", "SSNOOK", "TV", 1987, 8.9, "Australian"],
  ["Kieran Culkin", "KCULKIN", "TV", 1982, 10.4, "American"],
  ["Brian Cox", "BCOX", "TV", 1946, 7.1, "British"],
  ["Matthew Macfadyen", "MMACFADYEN", "TV", 1974, 6.8, "British"],
  ["Jennifer Coolidge", "JCOOLIDGE", "TV", 1961, 9.3, "American"],
  ["Quinta Brunson", "QBRUNSON", "TV", 1989, 10.7, "American"],
  ["Donald Glover", "DGLOVER", "TV", 1983, 11.2, "American"],
  ["Andy Samberg", "ASAMBERG", "TV", 1978, 6.5, "American"],
  ["Bill Hader", "BHADER", "TV", 1978, 7.4, "American"],
  ["Jason Sudeikis", "JSUDEIKIS", "TV", 1975, 8.3, "American"],
  ["Brett Goldstein", "BGOLDSTEIN", "TV", 1980, 7.1, "British"],
  ["Hannah Waddingham", "HWADDINGHAM", "TV", 1974, 9.2, "British"],
  ["Aubrey Plaza", "APLAZA", "TV", 1984, 11.5, "American"],
  ["Elizabeth Olsen", "EOLSEN", "TV", 1989, 9.8, "American"],
  ["Evan Peters", "EPETERS", "TV", 1987, 8.6, "American"],
  ["Sarah Paulson", "SPAULSON", "TV", 1974, 6.9, "American"],
  ["Kaley Cuoco", "KCUOCO", "TV", 1985, 5.4, "American"],
  ["Phoebe Waller-Bridge", "PWB", "TV", 1985, 6.6, "British"],
  ["Michaela Coel", "MCOEL", "TV", 1987, 7.5, "British"],
  ["Olivia Cooke", "OCOOKE", "TV", 1993, 8.2, "British"],
  ["Ncuti Gatwa", "NCUTI", "TV", 1992, 10.7, "British"],
  ["Jenna Coleman", "JCOLEMAN", "TV", 1986, 5.9, "British"],
  ["David Tennant", "DTENNANT", "TV", 1971, 7.2, "British"],
  ["Matt Smith", "MATTS", "TV", 1982, 6.4, "British"],
  ["Bella Ramsey", "BRAMSEY", "TV", 2003, 10.1, "British"],
  ["Nicola Coughlan", "NCOUGHLAN", "TV", 1987, 12.8, "Irish"],
  ["Simone Ashley", "SASHLEY", "TV", 1995, 10.4, "British"],
  ["Jonathan Bailey", "JBAILEY", "TV", 1988, 11.1, "British"],
  ["Rege-Jean Page", "RJPAGE", "TV", 1988, 8.6, "British"],
  ["Kit Connor", "KITCONNOR", "TV", 2004, 9.7, "British"],
  ["Joe Locke", "JLOCKE", "TV", 2003, 7.8, "British"],
  ["Yasmin Finney", "YFINNEY", "TV", 2003, 7.4, "British"],
  ["Kim Kardashian", "KIMK", "TV", 1980, 12.9, "American"],
  ["Khloe Kardashian", "KHLOEK", "TV", 1984, 8.2, "American"],
  ["Kris Jenner", "KRISJ", "TV", 1955, 7.9, "American"],
  ["RuPaul", "RUPAUL", "TV", 1960, 8.4, "American"],
  ["Jimmy Fallon", "JFALLON", "TV", 1974, 5.8, "American"],
  ["Jimmy Kimmel", "JKIMMEL", "TV", 1967, 6.1, "American"],
  ["Stephen Colbert", "SCOLBERT", "TV", 1964, 5.2, "American"],
  ["John Oliver", "JOLIVER", "TV", 1977, 7.6, "British"],
  ["Oprah Winfrey", "OPRAH", "TV", 1954, 6.9, "American"],
  ["Ellen DeGeneres", "ELLEND", "TV", 1958, 3.1, "American"],
  ["Drew Barrymore", "DBARRYMORE", "TV", 1975, 7.7, "American"],
  ["Kelly Clarkson", "KCLARKSON", "TV", 1982, 8.6, "American"],
  ["Guy Fieri", "GFIERI", "TV", 1968, 6.3, "American"],
  ["Simon Cowell", "SCOWELL", "TV", 1959, 4.7, "British"],
  ["Bear Grylls", "BGRYLLS", "TV", 1974, 5.3, "British"],
  ["Claudia Winkleman", "CWINKLE", "TV", 1972, 5.4, "British"],
  ["Alison Hammond", "AHAMMOND", "TV", 1975, 6.1, "British"],
  ["Graham Norton", "GNORTON", "TV", 1963, 4.3, "Irish"],
  ["Stacey Solomon", "SSOLOMON", "TV", 1989, 6.8, "British"],
  ["Rylan Clark", "RYLAN", "TV", 1989, 4.1, "British"],
  ["Davina McCall", "DMCCALL", "TV", 1967, 4.8, "British"],
  ["Martin Lewis", "MLEWIS", "TV", 1972, 7.3, "British"],
  ["Louis Theroux", "LTHEROUX", "TV", 1970, 8.5, "British"],
  ["Stephen Graham", "SGRAHAM", "TV", 1973, 8.1, "British"],
  ["Vicky McClure", "VMCCLURE", "TV", 1983, 4.5, "British"],
  ["Keeley Hawes", "KHAWES", "TV", 1976, 4.2, "British"],
  ["Suranne Jones", "SJONES", "TV", 1978, 4.8, "British"],
  ["Sarah Lancashire", "SLANCASHIRE", "TV", 1964, 6.7, "British"],

  // FILM (American & Global Screen Titans)
  ["Leonardo DiCaprio", "LEOD", "Film", 1974, 11.4, "American"],
  ["Brad Pitt", "BRADPITT", "Film", 1963, 9.8, "American"],
  ["Tom Cruise", "TCRUISE", "Film", 1962, 10.3, "American"],
  ["Dwayne Johnson", "THEROCK", "Film", 1972, 12.1, "American"],
  ["Ryan Reynolds", "RREYNOLDS", "Film", 1976, 14.5, "Canadian"],
  ["Will Smith", "WSMITH", "Film", 1968, 7.3, "American"],
  ["Denzel Washington", "DENZEL", "Film", 1954, 8.7, "American"],
  ["Keanu Reeves", "KREEVES", "Film", 1964, 11.8, "Canadian"],
  ["Scarlett Johansson", "SCARLETT", "Film", 1984, 11.2, "American"],
  ["Jennifer Lawrence", "JLAWRENCE", "Film", 1990, 10.6, "American"],
  ["Anne Hathaway", "AHATHAWAY", "Film", 1982, 9.4, "American"],
  ["Natalie Portman", "NPORTMAN", "Film", 1981, 8.9, "American"],
  ["Emma Stone", "ESTONE", "Film", 1988, 13.7, "American"],
  ["Michael B. Jordan", "MBJORDAN", "Film", 1987, 10.9, "American"],
  ["Glen Powell", "GPOWELL", "Film", 1988, 14.8, "American"],
  ["Chris Pratt", "CPRATT", "Film", 1979, 9.1, "American"],
  ["Chris Evans", "CEVANS", "Film", 1981, 8.5, "American"],
  ["Chris Hemsworth", "CHEMS", "Film", 1983, 10.2, "Australian"],
  ["Timothee Chalamet", "CHALAMET", "Film", 1995, 15.4, "American"],
  ["Austin Butler", "ABUTLER", "Film", 1991, 10.9, "American"],
  ["Margot Robbie", "MROBBIE", "Film", 1990, 13.5, "Australian"],
  ["Ryan Gosling", "RGOSLING", "Film", 1980, 10.7, "Canadian"],
  ["Jacob Elordi", "JELORDI", "Film", 1997, 14.3, "Australian"],
  ["Greta Gerwig", "GGERWIG", "Film", 1983, 8.8, "American"],
  ["Denis Villeneuve", "DENISV", "Film", 1967, 7.9, "Canadian"],
  ["Emma Watson", "EWATSON", "Film", 1990, 5.8, "British"],
  ["Tom Holland", "THOLLAND", "Film", 1996, 12.4, "British"],
  ["Benedict Cumberbatch", "BCUMBER", "Film", 1976, 4.2, "British"],
  ["Keira Knightley", "KEIRA", "Film", 1985, 3.9, "British"],
  ["Carey Mulligan", "MULLIGAN", "Film", 1985, 3.3, "British"],
  ["Tilda Swinton", "TILDA", "Film", 1960, 2.8, "British"],
  ["Hugh Grant", "HUGHG", "Film", 1960, 3.1, "British"],
  ["Colin Firth", "CFIRTH", "Film", 1960, 2.6, "British"],
  ["Gary Oldman", "GOLDMAN", "Film", 1958, 3.5, "British"],
  ["Helen Mirren", "HMIRREN", "Film", 1945, 3.7, "British"],
  ["Jodie Comer", "JCOMER", "Film", 1993, 10.8, "British"],
  ["Vanessa Kirby", "VKIRBY", "Film", 1988, 5.6, "British"],
  ["Lashana Lynch", "LLYNCH", "Film", 1987, 5.3, "British"],
  ["Letitia Wright", "LWRIGHT", "Film", 1993, 6.2, "British"],
  ["Dev Patel", "DPATEL", "Film", 1990, 7.6, "British"],
  ["Henry Cavill", "HCAVILL", "Film", 1983, 8.7, "British"],
  ["Orlando Bloom", "OBLOOM", "Film", 1977, 3.8, "British"],
  ["Jason Statham", "JSTATHAM", "Film", 1967, 4.4, "British"],
  ["Daniel Craig", "DCRAIG", "Film", 1968, 4.9, "British"],
  ["Taron Egerton", "TEGERTON", "Film", 1989, 5.1, "British"],
  ["Anya Taylor-Joy", "ANYATJ", "Film", 1996, 13.2, "British"],
  ["Robert Pattinson", "RPATT", "Film", 1986, 6.6, "British"],
  ["Paul Mescal", "PMESCAL", "Film", 1996, 11.3, "Irish"],
  ["Saoirse Ronan", "SRONAN", "Film", 1994, 8.5, "Irish"],
  ["Barry Keoghan", "BKEOGHAN", "Film", 1992, 9.4, "Irish"],
  ["Andrew Scott", "ASCOTT", "Film", 1976, 8.9, "Irish"],
  ["Colin Farrell", "CFARRELL", "Film", 1976, 7.8, "Irish"],
  ["Florence Pugh", "FPUGH", "Film", 1996, 13.8, "British"],
  ["Daisy Edgar-Jones", "DEJONES", "Film", 1998, 9.2, "British"],
  ["Christopher Nolan", "CNOLAN", "Film", 1970, 9.6, "British"],
  ["Mia Goth", "MIAGOTH", "Film", 1993, 8.7, "British"],
  ["Harris Dickinson", "HDICKINSON", "Film", 1996, 6.7, "British"],
  ["Josh O'Connor", "JOCONNOR", "Film", 1990, 6.5, "British"],
  ["Tom Hardy", "THARDY", "Film", 1977, 6.9, "British"],
  ["Kate Winslet", "KWINSLET", "Film", 1975, 5.6, "British"],
  ["Emily Blunt", "EBLUNT", "Film", 1983, 9.5, "British"],
  ["Lily James", "LJAMES", "Film", 1989, 6.5, "British"],
  ["John Boyega", "JBOYEGA", "Film", 1992, 6.9, "British"],
  ["Will Poulter", "WPOULTER", "Film", 1993, 6.2, "British"],
  ["Nicholas Hoult", "NHOULT", "Film", 1989, 5.5, "British"],
  ["Tom Hiddleston", "THIDDLES", "Film", 1981, 6.1, "British"],
  ["Eddie Redmayne", "EREDMAYNE", "Film", 1982, 4.8, "British"],
  ["Gemma Chan", "GCHAN", "Film", 1982, 5.4, "British"],
  ["Sophie Turner", "STURNER", "Film", 1996, 6.7, "British"],

  // MUSIC (American, British & Global Chart Toppers)
  ["Eminem", "EMINEM", "Music", 1972, 11.8, "American"],
  ["Justin Bieber", "JBIEBER", "Music", 1994, 9.7, "Canadian"],
  ["Bruno Mars", "BRUNOMARS", "Music", 1985, 13.2, "American"],
  ["SZA", "SZA", "Music", 1989, 13.5, "American"],
  ["Doja Cat", "DOJACAT", "Music", 1995, 12.1, "American"],
  ["Megan Thee Stallion", "THEESTALLION", "Music", 1995, 11.4, "American"],
  ["Cardi B", "CARDIB", "Music", 1992, 10.3, "American"],
  ["Nicki Minaj", "NICKIMINAJ", "Music", 1982, 9.9, "American"],
  ["Lana Del Rey", "LANADELREY", "Music", 1985, 12.6, "American"],
  ["Frank Ocean", "FRANKOCEAN", "Music", 1987, 10.8, "American"],
  ["Tyler, The Creator", "TYLER", "Music", 1991, 13.4, "American"],
  ["Snoop Dogg", "SNOOPDOGG", "Music", 1971, 9.6, "American"],
  ["Jay-Z", "JAYZ", "Music", 1969, 7.8, "American"],
  ["Bad Bunny", "BADBUNNY", "Music", 1994, 14.1, "Puerto Rican"],
  ["Peso Pluma", "PESOPLUMA", "Music", 1999, 12.7, "Mexican"],
  ["Sabrina Carpenter", "SCARPENTER", "Music", 1999, 15.6, "American"],
  ["Olivia Rodrigo", "ORODRIGO", "Music", 2003, 14.1, "American"],
  ["Billie Eilish", "BEILISH", "Music", 2001, 12.9, "American"],
  ["Chappell Roan", "CHAPPELL", "Music", 1998, 16.2, "American"],
  ["The Weeknd", "THEWEEKND", "Music", 1990, 11.5, "Canadian"],
  ["Drake", "DRAKE", "Music", 1986, 9.8, "Canadian"],
  ["Post Malone", "POSTMALONE", "Music", 1995, 8.1, "American"],
  ["Kendrick Lamar", "KENDRICK", "Music", 1987, 13.7, "American"],
  ["Travis Scott", "TRAVISS", "Music", 1991, 10.4, "American"],
  ["Jack Harlow", "JACKHARLOW", "Music", 1998, 7.2, "American"],
  ["Beyonce", "BEYONCE", "Music", 1981, 12.3, "American"],
  ["Katy Perry", "KPERRY", "Music", 1984, 5.1, "American"],
  ["Lady Gaga", "LADYGAGA", "Music", 1986, 9.4, "American"],
  ["Ariana Grande", "ARIANA", "Music", 1993, 11.9, "American"],
  ["Elton John", "ELTON", "Music", 1947, 4.9, "British"],
  ["Robbie Williams", "ROBBIE", "Music", 1974, 4.7, "British"],
  ["Jessie J", "JESSIEJ", "Music", 1988, 3.6, "British"],
  ["Rita Ora", "RITAORA", "Music", 1990, 5.2, "British"],
  ["Sam Smith", "SAMSMITH", "Music", 1992, 6.8, "British"],
  ["Florence Welch", "FLORENCE", "Music", 1986, 4.1, "British"],
  ["Liam Gallagher", "LIAMG", "Music", 1972, 2.9, "British"],
  ["Noel Gallagher", "NOELG", "Music", 1967, 2.6, "British"],
  ["Damon Albarn", "DAMON", "Music", 1968, 2.2, "British"],
  ["Skepta", "SKEPTA", "Music", 1982, 7.4, "British"],
  ["Dave", "SANTANDAVE", "Music", 1998, 10.3, "British"],
  ["Central Cee", "CENTRALC", "Music", 1998, 12.1, "British"],
  ["Little Simz", "LITTLESIMZ", "Music", 1994, 8.2, "British"],
  ["Jorja Smith", "JORJASMITH", "Music", 1997, 6.4, "British"],
  ["Raye", "RAYE", "Music", 1997, 11.6, "British"],
  ["Charli XCX", "CHARLI", "Music", 1992, 14.5, "British"],
  ["Mabel", "MABEL", "Music", 1996, 3.8, "British"],
  ["Anne-Marie", "ANNEMARIE", "Music", 1991, 4.4, "British"],
  ["Lewis Capaldi", "LEWISC", "Music", 1996, 7.9, "British"],
  ["Tom Grennan", "TOMG", "Music", 1995, 5.1, "British"],
  ["Yungblud", "YUNGBLUD", "Music", 1997, 9.6, "British"],
  ["FKA twigs", "FKATWIGS", "Music", 1988, 6.7, "British"],
  ["M.I.A.", "MIA", "Music", 1975, 2.1, "British"],
  ["Shania Twain", "SHANIA", "Music", 1965, 1.9, "Canadian"],
  ["Niall Horan", "NIALL", "Music", 1993, 4.6, "Irish"],
  ["Zayn Malik", "ZAYN", "Music", 1993, 6.9, "British"],
  ["Louis Tomlinson", "LTOMLINSON", "Music", 1991, 5.4, "British"],
  ["Calvin Harris", "CALVINH", "Music", 1984, 6.1, "British"],
  ["Fred again..", "FREDAGAIN", "Music", 1993, 13.8, "British"],
  ["PinkPantheress", "PINKP", "Music", 2001, 11.2, "British"],
  ["Gorillaz", "GORILLAZ", "Music", 1998, 4.3, "British"],
  ["Coldplay", "COLDPLAY", "Music", 1997, 8.7, "British"],
  ["Muse", "MUSE", "Music", 1994, 3.4, "British"],
  ["Arctic Monkeys", "ARCTICM", "Music", 2002, 7.9, "British"],
  ["The 1975", "THE1975", "Music", 2002, 6.5, "British"],
  ["Arlo Parks", "ARLOPARKS", "Music", 2000, 5.8, "British"],
  ["Sam Fender", "SAMFENDER", "Music", 1994, 9.2, "British"],
  ["Declan McKenna", "DECLANMCK", "Music", 1998, 4.2, "British"],
  ["Beabadoobee", "BEABADOOBEE", "Music", 2000, 8.4, "British"],
  ["Burna Boy", "BURNABOY", "Music", 1991, 10.7, "Nigerian"],
  ["Wizkid", "WIZKID", "Music", 1990, 8.3, "Nigerian"],
  ["Asake", "ASAKE", "Music", 1995, 9.5, "Nigerian"],
  ["Rema", "REMA", "Music", 2000, 11.8, "Nigerian"],
  ["Tyla", "TYLA", "Music", 2002, 13.4, "South African"],
  ["Kylie Minogue", "KYLIE", "Music", 1968, 6.8, "Australian"],
  ["Troye Sivan", "TROYESIVAN", "Music", 1995, 8.9, "Australian"],

  // SPORT - BASKETBALL (NBA / WNBA)
  ["LeBron James", "LEBRON", "Sport", 1984, 11.2, "American"],
  ["Stephen Curry", "SCURRY", "Sport", 1988, 10.4, "American"],
  ["Giannis Antetokounmpo", "GIANNIS", "Sport", 1994, 12.8, "Greek"],
  ["Luka Doncic", "LUKADONCIC", "Sport", 1999, 13.4, "Slovenian"],
  ["Nikola Jokic", "JOKIC", "Sport", 1995, 12.1, "Serbian"],
  ["Victor Wembanyama", "WEMBY", "Sport", 2004, 16.5, "French"],
  ["Kevin Durant", "KDURANT", "Sport", 1988, 8.9, "American"],
  ["Anthony Edwards", "ANTEDWARDS", "Sport", 2001, 14.7, "American"],
  ["Jayson Tatum", "JTATUM", "Sport", 1998, 11.9, "American"],
  ["Ja Morant", "JAMORANT", "Sport", 1999, 12.2, "American"],
  ["Shai Gilgeous-Alexander", "SGA", "Sport", 1998, 13.8, "Canadian"],
  ["Jalen Brunson", "JBRUNSON", "Sport", 1996, 12.4, "American"],
  ["Donovan Mitchell", "DMITCHELLNBA", "Sport", 1996, 10.1, "American"],
  ["Devin Booker", "DBOOKER", "Sport", 1996, 10.7, "American"],
  ["Caitlin Clark", "CCLARK", "Sport", 2002, 17.8, "American"],
  ["Angel Reese", "AREESE", "Sport", 2002, 14.3, "American"],
  ["Sabrina Ionescu", "SIONESCU", "Sport", 1997, 10.8, "American"],
  ["A'ja Wilson", "AJAWILSON", "Sport", 1996, 13.9, "American"],
  ["Breanna Stewart", "BSTIEWIE", "Sport", 1994, 9.8, "American"],

  // SPORT - FOOTBALL / BASEBALL (NFL / MLB)
  ["Patrick Mahomes", "MAHOMES", "Sport", 1995, 9.8, "American"],
  ["Travis Kelce", "TKELCE", "Sport", 1989, 12.7, "American"],
  ["Lamar Jackson", "LAMARJ", "Sport", 1997, 11.5, "American"],
  ["Josh Allen", "JOSHALLEN", "Sport", 1996, 10.9, "American"],
  ["Joe Burrow", "JBURROW", "Sport", 1996, 9.7, "American"],
  ["Justin Jefferson", "JJEFFERSON", "Sport", 1999, 11.2, "American"],
  ["Saquon Barkley", "SBARKLEY", "Sport", 1997, 12.3, "American"],
  ["C.J. Stroud", "CJSTROUD", "Sport", 2001, 13.1, "American"],
  ["Tyreek Hill", "TYREEKHILL", "Sport", 1994, 9.5, "American"],
  ["Shohei Ohtani", "OHTANI", "Sport", 1994, 18.2, "Japanese"],
  ["Aaron Judge", "AJUDGE", "Sport", 1992, 13.8, "American"],
  ["Juan Soto", "JUANSOTO", "Sport", 1998, 12.6, "Dominican"],
  ["Mookie Betts", "MBETTS", "Sport", 1992, 9.4, "American"],
  ["Elly De La Cruz", "EDELACRUZ", "Sport", 2002, 14.4, "Dominican"],
  ["Bryce Harper", "BHARPER", "Sport", 1992, 10.8, "American"],
  ["Freddie Freeman", "FFREEMAN", "Sport", 1989, 11.2, "American"],

  // SPORT - MOTORSPORT (F1 & MotoGP)
  ["Lewis Hamilton", "HAMILTON", "Sport", 1985, -1.7, "British"],
  ["Lando Norris", "LNORRIS", "Sport", 1999, 13.6, "British"],
  ["George Russell", "GRUSSELL", "Sport", 1998, 8.2, "British"],
  ["Max Verstappen", "VERSTAPPEN", "Sport", 1997, 12.1, "Dutch"],
  ["Charles Leclerc", "LECLERC", "Sport", 1997, 11.5, "Monegasque"],
  ["Oscar Piastri", "PIASTRI", "Sport", 2001, 10.9, "Australian"],
  ["Carlos Sainz", "SAINZ", "Sport", 1994, 7.8, "Spanish"],
  ["Fernando Alonso", "ALONSO", "Sport", 1981, 6.4, "Spanish"],
  ["Oliver Bearman", "OBEARMAN", "Sport", 2005, 12.8, "British"],
  ["Kimi Antonelli", "KANTONELLI", "Sport", 2006, 13.5, "Italian"],
  ["Franco Colapinto", "COLAPINTO", "Sport", 2003, 14.2, "Argentine"],
  ["Pierre Gasly", "GASLY", "Sport", 1996, 7.1, "French"],
  ["Marc Marquez", "MMARQUEZ", "Sport", 1993, 11.8, "Spanish"],
  ["Francesco Bagnaia", "BAGNAIA", "Sport", 1997, 9.3, "Italian"],
  ["Jorge Martin", "JMARTIN", "Sport", 1998, 11.1, "Spanish"],
  ["Pedro Acosta", "PACOSTA", "Sport", 2004, 12.6, "Spanish"],

  // SPORT - COMBAT (Boxing & MMA / UFC)
  ["Tyson Fury", "FURY", "Sport", 1988, 5.8, "British"],
  ["Anthony Joshua", "AJOSHUA", "Sport", 1989, 7.1, "British"],
  ["Oleksandr Usyk", "USYK", "Sport", 1987, 11.3, "Ukrainian"],
  ["Canelo Alvarez", "CANELO", "Sport", 1990, 8.4, "Mexican"],
  ["Katie Taylor", "KTAYLOR", "Sport", 1986, 6.9, "Irish"],
  ["Naoya Inoue", "NINOUE", "Sport", 1993, 12.9, "Japanese"],
  ["Gervonta Davis", "TANKDAVIS", "Sport", 1994, 13.5, "American"],
  ["Conor McGregor", "MCGREGOR", "Sport", 1988, 13.2, "Irish"],
  ["Jon Jones", "JONJONES", "Sport", 1987, 10.4, "American"],
  ["Islam Makhachev", "MAKHACHEV", "Sport", 1991, 11.7, "Russian"],
  ["Alex Pereira", "PEREIRA", "Sport", 1987, 15.6, "Brazilian"],
  ["Sean O'Malley", "SOMALLEY", "Sport", 1994, 12.4, "American"],
  ["Israel Adesanya", "ADESANYA", "Sport", 1989, 9.5, "New Zealander"],
  ["Ilia Topuria", "TOPURIA", "Sport", 1997, 16.1, "Spanish"],
  ["Khamzat Chimaev", "CHIMAEV", "Sport", 1994, 13.8, "Russian"],
  ["Paddy Pimblett", "PADDYP", "Sport", 1995, 12.3, "British"],
  ["Max Holloway", "MHOLLOWAY", "Sport", 1991, 14.1, "American"],

  // SPORT - TENNIS & GOLF
  ["Carlos Alcaraz", "ALCARAZ", "Sport", 2003, 14.7, "Spanish"],
  ["Jannik Sinner", "SINNER", "Sport", 2001, 13.9, "Italian"],
  ["Novak Djokovic", "DJOKOVIC", "Sport", 1987, 8.5, "Serbian"],
  ["Alexander Zverev", "AZVEREV", "Sport", 1997, 9.1, "German"],
  ["Daniil Medvedev", "MEDVEDEV", "Sport", 1996, 8.7, "Russian"],
  ["Jack Draper", "JDRAPER", "Sport", 2001, 10.5, "British"],
  ["Coco Gauff", "CGAUFF", "Sport", 2004, 12.2, "American"],
  ["Iga Swiatek", "SWIATEK", "Sport", 2001, 11.1, "Polish"],
  ["Aryna Sabalenka", "SABALENKA", "Sport", 1998, 10.6, "Belarusian"],
  ["Emma Raducanu", "RADUCANU", "Sport", 2002, 6.6, "British"],
  ["Andy Murray", "MURRAY", "Sport", 1987, 3.2, "British"],
  ["Scottie Scheffler", "SCHEFFLER", "Sport", 1996, 14.1, "American"],
  ["Bryson DeChambeau", "DECHAMBEAU", "Sport", 1993, 13.7, "American"],
  ["Rory McIlroy", "RMCILROY", "Sport", 1989, 4.6, "British"],
  ["Jon Rahm", "JONRAHM", "Sport", 1994, 8.6, "Spanish"],
  ["Tiger Woods", "TWOODS", "Sport", 1975, 7.2, "American"],
  ["Viktor Hovland", "VHOVLAND", "Sport", 1997, 8.9, "Norwegian"],
  ["Xander Schauffele", "XSCHAUFFELE", "Sport", 1993, 12.5, "American"],
  ["Tommy Fleetwood", "TFLEETWOOD", "Sport", 1991, 7.4, "British"],

  // SPORT - SOCCER / GLOBAL FOOTBALL
  ["Lionel Messi", "MESSI", "Sport", 1987, 10.8, "Argentine"],
  ["Kylian Mbappe", "MBAPPE", "Sport", 1998, 14.5, "French"],
  ["Erling Haaland", "HAALAND", "Sport", 2000, 13.9, "Norwegian"],
  ["Vinicius Jr", "VINICIUS", "Sport", 2000, 13.1, "Brazilian"],
  ["Lamine Yamal", "LAMINE", "Sport", 2007, 16.9, "Spanish"],
  ["Neymar Jr", "NEYMAR", "Sport", 1992, 7.4, "Brazilian"],
  ["Son Heung-min", "SONNY", "Sport", 1992, 8.1, "South Korean"],
  ["Mohamed Salah", "MOSALAH", "Sport", 1992, 10.5, "Egyptian"],
  ["Kevin De Bruyne", "KDB", "Sport", 1991, 7.8, "Belgian"],
  ["Rodri", "RODRI", "Sport", 1996, 13.2, "Spanish"],
  ["Marcus Rashford", "RASHFORD", "Sport", 1997, 8.4, "British"],
  ["Harry Kane", "HKANE", "Sport", 1993, 4.3, "British"],
  ["Raheem Sterling", "STERLING", "Sport", 1994, 2.7, "British"],
  ["Phil Foden", "FODEN", "Sport", 2000, 10.2, "British"],
  ["Declan Rice", "RICE", "Sport", 1999, 7.1, "British"],
  ["Jack Grealish", "GREALISH", "Sport", 1995, 5.4, "British"],
  ["Cole Palmer", "CPALMER", "Sport", 2002, 14.8, "British"],
  ["Kobbie Mainoo", "MAINOO", "Sport", 2005, 12.4, "British"],
  ["Ollie Watkins", "OWATKINS", "Sport", 1995, 7.6, "British"],
  ["Anthony Gordon", "AGORDON", "Sport", 2001, 6.9, "British"],
  ["Trent Alexander-Arnold", "TAA", "Sport", 1998, 8.7, "British"],
  ["Mary Earps", "EARPS", "Sport", 1993, 9.8, "British"],
  ["Lauren James", "LAURENJ", "Sport", 2001, 8.8, "British"],
  ["Beth Mead", "BETHMEAD", "Sport", 1995, 4.1, "British"],
  ["Millie Bright", "MBRIGHT", "Sport", 1993, 3.7, "British"],
  ["Lucy Bronze", "BRONZE", "Sport", 1991, 4.6, "British"],
  ["Alessia Russo", "RUSSO", "Sport", 1999, 9.1, "British"],
  ["Chloe Kelly", "CKELLY", "Sport", 1998, 7.8, "British"],
  ["Alexia Putellas", "PUTELLAS", "Sport", 1994, 8.3, "Spanish"],
  ["Aitana Bonmati", "BONMATI", "Sport", 1998, 11.4, "Spanish"],
  ["Sam Kerr", "SAMKERR", "Sport", 1993, 7.2, "Australian"],

  // CRICKET & RUGBY & OLYMPICS
  ["Virat Kohli", "VKOHLI", "Sport", 1988, 15.9, "Indian"],
  ["Rohit Sharma", "RSHARMA", "Sport", 1987, 11.3, "Indian"],
  ["Jasprit Bumrah", "JBUMRAH", "Sport", 1993, 12.4, "Indian"],
  ["Pat Cummins", "PCUMMINS", "Sport", 1993, 9.8, "Australian"],
  ["Ben Stokes", "BSTOKES", "Sport", 1991, 3.9, "British"],
  ["Joe Root", "JROOT", "Sport", 1990, 3.1, "British"],
  ["Antoine Dupont", "ADUPONT", "Sport", 1996, 14.9, "French"],
  ["Caelan Doris", "CDORIS", "Sport", 1998, 8.2, "Irish"],
  ["Marcus Smith", "MSMITHRUG", "Sport", 1999, 9.4, "British"],
  ["Siya Kolisi", "SKOLISI", "Sport", 1991, 10.7, "South African"],
  ["Simone Biles", "SBILES", "Sport", 1997, 16.8, "American"],
  ["Leon Marchand", "LMARCHAND", "Sport", 2002, 15.3, "French"],
  ["Katie Ledecky", "KLEDECKY", "Sport", 1997, 10.1, "American"],
  ["Noah Lyles", "NLYLES", "Sport", 1997, 14.2, "American"],
  ["Mondo Duplantis", "DUPLANTIS", "Sport", 1999, 15.7, "Swedish"],
  ["Mikaela Shiffrin", "MSHIFFRIN", "Sport", 1995, 11.2, "American"],
  ["Eileen Gu", "EILEENGU", "Sport", 2003, 13.4, "Chinese"],
  ["Luke Littler", "LITTLER", "Sport", 2007, 15.8, "British"],
  ["Luke Humphries", "HUMPHRIES", "Sport", 1995, 8.9, "British"],
  ["Michael van Gerwen", "MVG", "Sport", 1989, 5.2, "Dutch"],
  ["Tom Daley", "TDALEY", "Sport", 1994, 6.2, "British"],
  ["Adam Peaty", "PEATY", "Sport", 1994, 4.8, "British"],
  ["Keely Hodgkinson", "KEELYH", "Sport", 2002, 13.5, "British"],
  ["Katarina Johnson-Thompson", "KJT", "Sport", 1993, 7.3, "British"],
  ["Dina Asher-Smith", "DAS", "Sport", 1995, 5.5, "British"],

  // FASHION & BEAUTY
  ["Paloma Elsesser", "PALOMAE", "Fashion", 1992, 6.8, "American"],
  ["Gigi Hadid", "GIGIH", "Fashion", 1995, 8.2, "American"],
  ["Kendall Jenner", "KJENNER", "Fashion", 1995, 11.4, "American"],
  ["Hailey Bieber", "HBIEBER", "Fashion", 1996, 12.9, "American"],
  ["Kylie Jenner", "KYLIEJ", "Fashion", 1997, 10.3, "American"],
  ["Naomi Campbell", "NAOMIC", "Fashion", 1970, 6.4, "British"],
  ["Kate Moss", "KATEMOSS", "Fashion", 1974, 5.8, "British"],
  ["Cara Delevingne", "CARAD", "Fashion", 1992, 7.3, "British"],
  ["Alexa Chung", "ALEXAC", "Fashion", 1983, 4.9, "British"],
  ["Jourdan Dunn", "JDUNN", "Fashion", 1990, 5.1, "British"],
  ["Adwoa Aboah", "ADWOAA", "Fashion", 1992, 4.6, "British"],
  ["Victoria Beckham", "VBECKHAM", "Fashion", 1974, 5.5, "British"],
  ["Jonathan Anderson", "JWANDERSON", "Fashion", 1984, 8.7, "British"],
  ["Daniel Lee", "DANIELLEE", "Fashion", 1986, 6.2, "British"],
  ["Iris Law", "IRISLAW", "Fashion", 2000, 7.1, "British"],
  ["Lila Moss", "LILAMOSS", "Fashion", 2002, 6.9, "British"],
  ["Mia Regan", "MIAREGAN", "Fashion", 2002, 5.4, "British"],
  ["Matty Bovan", "MBOVAN", "Fashion", 1990, 4.1, "British"],

  // DIGITAL & CREATORS
  ["IShowSpeed", "SPEED", "Digital", 2005, 16.4, "American"],
  ["Kai Cenat", "KAICENAT", "Digital", 2001, 15.8, "American"],
  ["Emma Chamberlain", "ECHAMBERLAIN", "Digital", 2001, 10.2, "American"],
  ["Alex Cooper", "ACOOPER", "Digital", 1994, 11.9, "American"],
  ["Alix Earle", "ALIXEARLE", "Digital", 2000, 12.5, "American"],
  ["Joe Rogan", "JROGAN", "Digital", 1967, 10.8, "American"],
  ["Steven Bartlett", "SBARTLETT", "Digital", 1992, 8.7, "British"],
  ["Sidemen", "SIDEMEN", "Digital", 1990, 9.4, "British"],
  ["W2S", "W2S", "Digital", 1996, 7.8, "British"],
  ["Miniminter", "MINIMINTER", "Digital", 1992, 6.9, "British"],
  ["TBJZL", "TBJZL", "Digital", 1993, 5.7, "British"],
  ["Behzinga", "BEHZINGA", "Digital", 1995, 6.4, "British"],
  ["Zerkaa", "ZERKAA", "Digital", 1992, 5.5, "British"],
  ["Vikkstar123", "VIKKSTAR", "Digital", 1995, 7.1, "British"],
  ["TommyInnit", "TOMMYINNIT", "Digital", 2004, 8.6, "British"],
  ["GeorgeNotFound", "GEORGENF", "Digital", 1996, 6.2, "British"],
  ["Wilbur Soot", "WILBURS", "Digital", 1996, 4.3, "British"],
  ["DanTDM", "DANTDM", "Digital", 1991, 6.8, "British"],
  ["Chunkz", "CHUNKZ", "Digital", 1996, 9.8, "British"],
  ["Yung Filly", "YUNGFILLY", "Digital", 1995, 8.4, "British"],
  ["Harry Pinero", "HPINERO", "Digital", 1991, 6.7, "British"],
  ["Darkest Man", "DARKESTMAN", "Digital", 1997, 7.3, "British"],
  ["Nella Rose", "NELLAROSE", "Digital", 1997, 8.9, "British"],
  ["GK Barry", "GKBARRY", "Digital", 1999, 11.4, "British"],
  ["Madeline Argy", "MARGY", "Digital", 2000, 9.6, "British"],
  ["Max Fosh", "MAXFOSH", "Digital", 1995, 9.2, "British"],
  ["Niko Omilana", "NIKOO", "Digital", 1998, 10.1, "British"],
  ["ChrisMD", "CHRISMD", "Digital", 1996, 6.5, "British"],

  // COMEDY
  ["Mo Gilligan", "MOGILL", "Comedy", 1988, 5.2, "British"],
  ["Joe Lycett", "JLYCETT", "Comedy", 1988, 5.5, "British"],
  ["Jack Whitehall", "JWHITEHALL", "Comedy", 1988, 5.6, "British"],
  ["Katherine Ryan", "KRYAN", "Comedy", 1983, 4.5, "Canadian"],
  ["Sarah Millican", "SMILLICAN", "Comedy", 1975, 3.8, "British"],
  ["Dawn French", "DFRENCH", "Comedy", 1957, 2.7, "British"],
  ["Jennifer Saunders", "JSAUNDERS", "Comedy", 1958, 2.8, "British"],
  ["Matt Lucas", "MLUCAS", "Comedy", 1974, 3.1, "British"],
  ["Noel Fielding", "NFIELDING", "Comedy", 1973, 3.7, "British"],
  ["Ricky Gervais", "RGERVAIS", "Comedy", 1961, 5.3, "British"],
  ["Steve Coogan", "SCOOGAN", "Comedy", 1965, 3.5, "British"],
  ["Rob Brydon", "RBRYDON", "Comedy", 1965, 2.7, "British"],
  ["David Mitchell", "DMITCHELL", "Comedy", 1974, 3.9, "British"],
  ["Victoria Coren Mitchell", "VCM", "Comedy", 1972, 3.3, "British"],
  ["Jimmy Carr", "JCARR", "Comedy", 1972, 3.4, "British"],
  ["Greg Davies", "GDAVIES", "Comedy", 1968, 4.4, "British"],
  ["Richard Ayoade", "RAYOADE", "Comedy", 1977, 3.2, "British"],
  ["Munya Chawawa", "MCHAWAWA", "Comedy", 1992, 5.6, "British"],
  ["Bob Mortimer", "BMORTIMER", "Comedy", 1959, 3.9, "British"],
  ["Fern Brady", "FERNBRADY", "Comedy", 1986, 6.1, "British"],
  ["Maisie Adam", "MAISIEADAM", "Comedy", 1994, 5.4, "British"],
  ["Phil Wang", "PHILWANG", "Comedy", 1990, 4.8, "British"],
  ["Ed Gamble", "EDGAMBLE", "Comedy", 1986, 5.2, "British"],
  ["Nish Kumar", "NISHKUMAR", "Comedy", 1985, 3.9, "British"],
  ["Josh Widdicombe", "JWIDDICOMBE", "Comedy", 1983, 4.2, "British"],
  ["Rob Beckett", "ROBBECKETT", "Comedy", 1986, 4.9, "British"],
  ["Guz Khan", "GUZKHAN", "Comedy", 1986, 5.8, "British"],

  // POLITICS & PUBLIC AFFAIRS
  ["Angela Rayner", "RAYNER", "Politics", 1980, 5.7, "British"],
  ["Rachel Reeves", "RREEVES", "Politics", 1979, 4.2, "British"],
  ["David Lammy", "LAMMY", "Politics", 1972, 3.8, "British"],
  ["Wes Streeting", "STREETING", "Politics", 1983, 4.4, "British"],
  ["Ed Miliband", "EMILIBAND", "Politics", 1969, 3.1, "British"],
  ["Kemi Badenoch", "BADENOCH", "Politics", 1980, 6.4, "British"],
  ["James Cleverly", "CLEVERLY", "Politics", 1969, 3.3, "British"],
  ["Suella Braverman", "BRAVERMAN", "Politics", 1980, 4.8, "British"],
  ["Jeremy Hunt", "JHUNT", "Politics", 1966, 2.5, "British"],
  ["Boris Johnson", "BORISJ", "Politics", 1964, 5.9, "British"],
  ["Theresa May", "TMAY", "Politics", 1956, 2.1, "British"],
  ["Tony Blair", "TBLAIR", "Politics", 1953, 3.4, "British"],
  ["Gordon Brown", "GBROWN", "Politics", 1951, 2.4, "British"],
  ["Ed Davey", "EDDAVEY", "Politics", 1965, 4.9, "British"],
  ["Carla Denyer", "DENYER", "Politics", 1985, 4.1, "British"],
  ["Adrian Ramsay", "ARAMSAY", "Politics", 1981, 3.2, "British"],
  ["John Swinney", "SWINNEY", "Politics", 1964, 2.9, "British"],
  ["Humza Yousaf", "HYOUSAF", "Politics", 1985, 3.6, "British"],
  ["Nicola Sturgeon", "STURGEON", "Politics", 1970, 3.7, "British"],
  ["Andy Burnham", "BURNHAM", "Politics", 1970, 5.2, "British"],
  ["Tracy Brabin", "BRABIN", "Politics", 1961, 2.8, "British"],
  ["Richard Tice", "RTICE", "Politics", 1964, 3.9, "British"],
];

function profileImage(ticker: string) {
  return `/api/celebrity-images/${encodeURIComponent(ticker)}`;
}

export const additionalCelebrityMarkets: AdditionalMarket[] = profiles.map(
  ([name, ticker, category, birthYear, change, nationality = "British"], index) => ({
    name,
    ticker: ticker.replace(/ /g, ""),
    category,
    birthYear,
    nationality,
    image: profileImage(ticker),
    change,
    signals: {
      socialFollowersMillions: Number((1.8 + (index % 24) * 0.95).toFixed(1)),
      hashtagViewsBillions: Number((0.9 + (index % 18) * 0.65).toFixed(1)),
      trendScore: 65 + (index % 33),
      monthlySearchesMillions: Number((1.4 + (index % 16) * 0.82).toFixed(1)),
      newsStories: 160 + (index % 22) * 45,
    },
  }),
);