import type { CelebrityMarket } from "./markets";

export type MarketMetadata = {
  isLiving: boolean;
  isTradeable: boolean;
  wikipediaTitle: string;
  sourceCategory: CelebrityMarket["category"];
  region: string;
  reviewedAt: string;
};

const customWikipediaTitles: Record<string, string> = {
  // POLITICIANS
  BORISJ: "Boris_Johnson",
  LTRUSS: "Liz_Truss",
  CORBYN: "Jeremy_Corbyn",
  CAMERON: "David_Cameron",
  TMAY: "Theresa_May",
  STREETING: "Wes_Streeting",
  REEVES: "Rachel_Reeves",
  RAYNER: "Angela_Rayner",
  BADENOCH: "Kemi_Badenoch",
  CLEVERLY: "James_Cleverly",
  PRITIP: "Priti_Patel",
  BRAVERMAN: "Suella_Braverman",
  EDDAVEY: "Ed_Davey",
  JSWINNEY: "John_Swinney",
  HUMZAY: "Humza_Yousaf",
  NSTURGEON: "Nicola_Sturgeon",
  BURNHAM: "Andy_Burnham",
  RORYS: "Rory_Stewart",
  ACAMPBELL: "Alastair_Campbell",
  TRUMP: "Donald_Trump",
  KAMALAH: "Kamala_Harris",
  JBIDEN: "Joe_Biden",
  OBAMA: "Barack_Obama",
  MACRON: "Emmanuel_Macron",
  STARMER: "Keir_Starmer",
  SUNAK: "Rishi_Sunak",
  FARAGE: "Nigel_Farage",
  SADIQ: "Sadiq_Khan",

  // UK TV ACTORS & ACTRESSES
  SLANCASHIRE: "Sarah_Lancashire",
  JNORTON: "James_Norton_(actor)",
  MCOMPSTON: "Martin_Compston",
  VMCCLURE: "Vicky_McClure",
  ADUNBAR: "Adrian_Dunbar",
  KHAWES: "Keeley_Hawes",
  RMADDEN: "Richard_Madden",
  JCOMER: "Jodie_Comer",
  SJONES: "Suranne_Jones",
  DTENNANT: "David_Tennant",
  MSMITH_ACTOR: "Matt_Smith_(actor)",
  NCUTI: "Ncuti_Gatwa",
  OOKE: "Olivia_Cooke",
  EDARCY: "Emma_D'Arcy",
  KHARINGTON: "Kit_Harington",
  ECLARKE: "Emilia_Clarke",
  PMESCAL: "Paul_Mescal",
  DEDGARJONES: "Daisy_Edgar-Jones",
  NCOUGHLAN: "Nicola_Coughlan",
  LNEWTON: "Luke_Newton",
  JBAILEY: "Jonathan_Bailey_(actor)",
  PDYNEVOR: "Phoebe_Dynevor",
  RJPAGE: "Regé-Jean_Page",
  SASHLEY: "Simone_Ashley",
  CTURNER: "Callum_Turner",
  BKEOGHAN: "Barry_Keoghan",
  JELORDI: "Jacob_Elordi",
  LWOODALL: "Leo_Woodall",
  AMOD: "Ambika_Mod",
  THEOJ: "Theo_James",
  KSCODELARIO: "Kaya_Scodelario",
  SGRAHAM: "Stephen_Graham",
  JOECOLE: "Joe_Cole_(actor)",
  SRUNDLE: "Sophie_Rundle",
  THARDY: "Tom_Hardy",
  LMANVILLE: "Lesley_Manville",
  ISTAUNTON: "Imelda_Staunton",
  DWEST: "Dominic_West",
  GANDERSON_ACT: "Gillian_Anderson",
  ABUTTERFIELD: "Asa_Butterfield",
  EMACKEY: "Emma_Mackey",
  CSWINDELLS: "Connor_Swindells",
  ALWOOD: "Aimee_Lou_Wood",
  JLOCKE: "Joe_Locke_(actor)",
  KCONNOR: "Kit_Connor",
  RJONES: "Ruth_Jones",
  JCORDEN: "James_Corden",
  RBRYDON: "Rob_Brydon",
  JPAGE: "Joanna_Page",
  ASTEADMAN: "Alison_Steadman",
  LLAMB: "Larry_Lamb",

  // PRESENTERS & BROADCASTERS
  CWINKLEMAN: "Claudia_Winkleman",
  GNORTON: "Graham_Norton",
  LTHEROUX: "Louis_Theroux",
  JROSS: "Jonathan_Ross",
  AHAMMOND: "Alison_Hammond",
  RYLAN: "Rylan_Clark",
  SSOLOMON: "Stacey_Solomon",
  JLYCETT: "Joe_Lycett",
  ROSMAN: "Richard_Osman",
  AARMSTRONG: "Alexander_Armstrong",
  JCARR: "Jimmy_Carr",
  MELG: "Mel_Giedroyc",
  SUEP: "Sue_Perkins",
  STOKSVIG: "Sandi_Toksvig",
  ACARR: "Alan_Carr",
  DMCCALL: "Davina_McCall",
  AJODUDU: "AJ_Odudu",
  WILLBEST: "Will_Best",
  LWHITMORE: "Laura_Whitmore",
  ISTIRLING: "Iain_Stirling",
  ABROOKER: "Alex_Brooker",
  JWIDDICOMBE: "Josh_Widdicombe",
  AHILLS: "Adam_Hills",
  RBECKETT: "Rob_Beckett",
  JDOMMETT: "Joel_Dommett",
  MOGILLIGAN: "Mo_Gilligan",
  MUNYAC: "Munya_Chawawa",
  CPACKHAM: "Chris_Packham",
  SREEVE: "Simon_Reeve_(presenter)",
  CBALDING: "Clare_Balding",
  GLOGAN: "Gabby_Logan",
  ALEXSCOTT: "Alex_Scott_(footballer,_born_1984)",
  LWOODS: "Laura_Woods_(presenter)",
  KELLYCATES: "Kelly_Cates",
  MAYAJAMA: "Maya_Jama",
  ANTDEC: "Ant_&_Dec",
  GORDONR: "Gordon_Ramsay",
  ATTENBOROUGH: "David_Attenborough",

  // FOOTBALLERS
  ODEGAARD: "Martin_Ødegaard",
  SALIBA: "William_Saliba",
  GABRIELM: "Gabriel_Magalhães",
  HAVERTZ: "Kai_Havertz",
  GREALISH: "Jack_Grealish",
  ENZOF: "Enzo_Fernández",
  NJACKSON: "Nicolas_Jackson",
  BRUNOF: "Bruno_Fernandes",
  GARNACHO: "Alejandro_Garnacho",
  AMAD: "Amad_Diallo",
  VANDIJK: "Virgil_van_Dijk",
  MACALLISTER: "Alexis_Mac_Allister",
  SZOBOSZLAI: "Dominik_Szoboszlai",
  LUISDIAZ: "Luis_Díaz_(footballer)",
  DARWINN: "Darwin_Núñez",
  BJOHNSON: "Brennan_Johnson",
  VANDEVEN: "Micky_van_de_Ven",
  SOLANKE: "Dominic_Solanke",
  OWATKINS: "Ollie_Watkins",
  DIBUMARTINEZ: "Emiliano_Martínez",
  ISAK: "Alexander_Isak",
  AGORDON: "Anthony_Gordon_(footballer)",
  BRUNOG: "Bruno_Guimarães",
  TONALI: "Sandro_Tonali",
  PAQUETA: "Lucas_Paquetá",
  MATETA: "Jean-Philippe_Mateta",
  CUNHA: "Matheus_Cunha",
  MBEUMO: "Bryan_Mbeumo",
  WISSA: "Yoane_Wissa",
  CHRISWOOD: "Chris_Wood_(footballer)",
  MGIBBSWHITE: "Morgan_Gibbs-White",
  LEWANDOWSKI: "Robert_Lewandowski",
  RAPHINHA: "Raphinha_(footballer,_born_1996)",
  PEDRI: "Pedri",
  GAVI: "Gavi_(footballer)",
  MUSIALA: "Jamal_Musiala",
  WIRTZ: "Florian_Wirtz",
  LAUTAROM: "Lautaro_Martínez",
  OSIMHEN: "Victor_Osimhen",
  KVARATSKHELIA: "Khvicha_Kvaratskhelia",
  LWILLIAMSON: "Leah_Williamson",
  BETHMEAD: "Beth_Mead",
  ARUSSO: "Alessia_Russo",
  MEARPS: "Mary_Earps",
  LJAMES: "Lauren_James",
  CKELLY: "Chloe_Kelly",
  SAMKERR: "Sam_Kerr",
  BONMATI: "Aitana_Bonmatí",
  APUTELLAS: "Alexia_Putellas",
  BELLINGHAM: "Jude_Bellingham",
  CR7: "Cristiano_Ronaldo",
  MESSI: "Lionel_Messi",
  MBAPPE: "Kylian_Mbappé",
  HAALAND: "Erling_Haaland",
  LAMINE: "Lamine_Yamal",
  VINICIUS: "Vinícius_Júnior",
  SONNY: "Son_Heung-min",
  MOSALAH: "Mohamed_Salah",
  KDB: "Kevin_De_Bruyne",
  RODRI: "Rodri_(footballer)",
  CPALMER: "Cole_Palmer",
  MAINOO: "Kobbie_Mainoo",
  FODEN: "Phil_Foden",
  RICE: "Declan_Rice",
  TAA: "Trent_Alexander-Arnold",
  HKANE: "Harry_Kane",
  SAKA: "Bukayo_Saka",
  RASHFORD: "Marcus_Rashford",

  // K-POP & MUSIC
  JUNGKOOK: "Jungkook",
  JIMIN: "Jimin",
  V_BTS: "V_(singer)",
  RMBTS: "RM_(musician)",
  SUGA: "Suga_(rapper)",
  JINBTS: "Jin_(singer)",
  JHOPE: "J-Hope",
  JENNIE: "Jennie_(singer)",
  LISAMUSIC: "Lisa_(rapper)",
  JISOO: "Jisoo",
  ROSEPARK: "Rosé_(singer)",
  STRAYKIDS: "Stray_Kids",
  FELIXSKZ: "Felix_(rapper)",
  NEWJEANS: "NewJeans",
  HANNINJ: "Hanni_(singer)",
  AESPA: "Aespa",
  KARINAAESPA: "Karina_(South_Korean_singer)",
  IU_LEE: "IU_(singer)",
  CHAEUNWOO: "Cha_Eun-woo",
  SEVENTEEN: "Seventeen_(South_Korean_band)",
  ENHYPEN: "Enhypen",
  TWICE: "Twice_(group)",
  NAYEON: "Nayeon",
  TSWIFT: "Taylor_Swift",
  ADELE: "Adele",
  DUALIPA: "Dua_Lipa",
  EDSHEERAN: "Ed_Sheeran",
  HSTYLES: "Harry_Styles",
  STORMZY: "Stormzy",
};

const reviewedExceptions: Record<string, Pick<MarketMetadata, "isLiving" | "isTradeable">> = {
  BOWIE: { isLiving: false, isTradeable: false },
  AMYWINE: { isLiving: false, isTradeable: false },
  FREDDIE: { isLiving: false, isTradeable: false },
  GMICHAEL: { isLiving: false, isTradeable: false },
  MSMITH: { isLiving: false, isTradeable: false },
};

const toWikipediaTitle = (market: CelebrityMarket) =>
  customWikipediaTitles[market.ticker] ?? market.name.replaceAll(" ", "_");

export function getMarketMetadata(market: CelebrityMarket): MarketMetadata {
  const exception = reviewedExceptions[market.ticker];

  return {
    isLiving: exception?.isLiving ?? true,
    isTradeable: exception?.isTradeable ?? true,
    wikipediaTitle: toWikipediaTitle(market),
    sourceCategory: market.category,
    region: market.nationality,
    reviewedAt: "2025-02-21",
  };
}

export function isEligibleMarket(market: CelebrityMarket) {
  const metadata = getMarketMetadata(market);
  return metadata.isLiving && metadata.isTradeable;
}